services:
  # 1. PostGIS Database
  db:
    image: postgis/postgis:15-3.3
    container_name: drone_db
    restart: always
    environment:
      POSTGRES_DB: drone_monitoring
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dronepassword_secure_99
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  # 2. FastAPI Backend
  backend:
    build:
      context: ../
      dockerfile: docker/Dockerfile.backend
    container_name: drone_backend
    restart: always
    environment:
      - DATABASE_URL=postgresql://postgres:dronepassword_secure_99@db:5432/drone_monitoring
      - SECRET_KEY=09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
    ports:
      - "8000:8000"
    volumes:
      - tiles_data:/var/www/tiles
    depends_on:
      - db

  # 3. Nginx + React Frontend
  frontend:
    build:
      context: ../
      dockerfile: docker/Dockerfile.frontend
    container_name: drone_frontend
    restart: always
    ports:
      - "80:80"
    volumes:
      - tiles_data:/var/www/tiles:ro
    depends_on:
      - backend

volumes:
  pgdata:
  tiles_data:
